site: Johannes Hagspiel
title: Johannes Hagspiel
description: A personal website.
googlewebfonts: Space+Grotesk:wght@400;500;700
lang: en-US
data-theme: dark # default theme "dark" | "light"

# URL settings
url: "https://johanneshagspiel.github.io/"
permalink: "https://johanneshagspiel.github.io/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-redirect-from

collections:
  pages:
    output: true
    permalink: /:name
  software-projects:
    output: true
    permalink: /software-projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "software-projects"
    values:
      layout: "software-projects"

relative_links:
  enabled:     true
  collections: false
